import type { User, InspectionReport } from '../types.ts';

export interface DbUser extends User {
  passwordHash: string;
  scannedHistoryTable: string;
}

export const DEFAULT_USERS: DbUser[] = [
  {
    id: 'id_gov_01',
    name: 'Rajesh Sharma (Inspector)',
    email: 'rajesh.sharma@consumeraffairs.gov.in',
    governmentId: 'GOV-LM-2024-889',
    passwordHash: 'officer123',
    role: 'official',
    department: 'Legal Metrology Enforcement Wing, New Delhi',
    scannedHistoryTable: 'history_gov_01',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788402960464_xg3q',
    name: 'Utkrishta Singoria (Enforcement Officer)',
    email: 'utkrishtasingoria@gmail.com',
    governmentId: 'GOV-LM-2026-901',
    passwordHash: '123456',
    role: 'official',
    department: 'Legal Metrology Enforcement Directorate, New Delhi',
    scannedHistoryTable: 'history_id_1788402960464_xg3q',
    createdAt: '2026-09-03T02:36:00.464Z',
  },
  {
    id: 'id_user_01',
    name: 'Anita Verma',
    email: 'anita.verma@example.com',
    passwordHash: 'user123',
    role: 'consumer',
    scannedHistoryTable: 'history_user_01',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788405108857_hpot',
    name: 'Sunil Verma',
    email: 'sunil.verma@gov.in',
    governmentId: 'GOV-LM-2026-104',
    passwordHash: 'password123',
    role: 'official',
    department: 'Metrology HQ',
    scannedHistoryTable: 'history_id_1788405108857_hpot',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788409112578_brpp',
    name: 'Audit Officer',
    email: 'auditofficer101@example.com',
    governmentId: 'DoCA-LM-2026-888',
    passwordHash: 'password123',
    role: 'official',
    department: 'Legal Metrology Enforcement Wing',
    scannedHistoryTable: 'history_id_1788409112578_brpp',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788402835454_pcqb',
    name: 'Sunita Rao',
    email: 'sunita.rao@example.com',
    passwordHash: 'password123',
    role: 'consumer',
    scannedHistoryTable: 'history_id_1788402835454_pcqb',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788409325508_7igh',
    name: 'utk',
    email: 'utkrishtacrazymaster@gmail.com',
    passwordHash: 'password123',
    role: 'consumer',
    scannedHistoryTable: 'history_id_1788409325508_7igh',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'id_1788409412760_1bba',
    name: 'Geeta Singoria',
    email: 'geetasingoria24@gmail.com',
    passwordHash: 'password123',
    role: 'consumer',
    scannedHistoryTable: 'history_id_1788409412760_1bba',
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_INSPECTIONS: InspectionReport[] = [
  {
    id: 'INS-2026-0091',
    userId: 'id_gov_01',
    userName: 'Rajesh Sharma (Inspector)',
    userRole: 'official',
    governmentId: 'GOV-LM-2024-889',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    productName: 'Tasty Crunch Classic Salted Potato Chips',
    category: 'Snacks & Confectionery',
    complianceScore: 100,
    complianceStatus: 'COMPLIANT',
    enforcementAction: 'VERIFIED_COMPLIANT',
    inspectorRemarks: 'Complete adherence to Legal Metrology Rules, 2011. Clean MRP and generic declaration.',
    imageUrls: ['https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80'],
    extractedData: {
      productName: 'Tasty Crunch Classic Salted Potato Chips',
      brandName: 'Tasty Crunch',
      genericCommodityName: 'Potato Chips',
      category: 'Snacks & Confectionery',
      manufacturerDetails: {
        name: 'Crispy Foods India Pvt. Ltd.',
        address: 'Plot 42, Hadapsar Industrial Estate, Pune, Maharashtra - 411013',
        isSpecified: true,
        isMarketerDifferent: true,
        marketerDetails: 'Tasty Crunch Foods Ltd., Mumbai',
        countryOfOrigin: 'India',
      },
      netQuantity: {
        declaredValue: '52 g',
        numericValue: 52,
        unit: 'g',
        isUnitValid: true,
        standardPackMatch: true,
        misleadingTermsUsed: [],
        clearSpaceCompliant: true,
      },
      mrpDetails: {
        declaredMRP: '₹ 20.00 (incl. of all taxes)',
        numericMRP: 20.0,
        hasInclAllTaxes: true,
        unitSalePrice: '₹ 0.38 / g',
        isStickerPasted: false,
        isAltered: false,
      },
      dates: {
        mfgDate: '09/2026',
        expiryDate: '03/2027',
        bestBefore: '6 Months from manufacture',
      },
      consumerCare: {
        hasConsumerCare: true,
        nameOrDesignation: 'Consumer Grievance Officer',
        phoneOrTollFree: '1800-111-4567',
        email: 'care@tastycrunch.co.in',
        postalAddress: 'Plot 42, Hadapsar Industrial Estate, Pune - 411013',
        completeness: 'COMPLETE',
      },
      languageAndVisibility: {
        isHindiOrEnglish: true,
        languagesDetected: ['English', 'Hindi'],
        isColorContrasting: true,
        fontSizeEstimatedPt: 10,
        isFontSizeAdequate: true,
        isMoldedOrBlown: false,
      },
      declarationsTable: [
        { field: 'commodityName', label: 'Name of Commodity', extractedValue: 'Potato Chips', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(b)', notes: 'Clearly declared generic commodity name.' },
        { field: 'mfgName', label: 'Manufacturer Name & Address', extractedValue: 'Crispy Foods India Pvt. Ltd., Pune - 411013', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(a)', notes: 'Full address with PIN code.' },
        { field: 'netQty', label: 'Net Quantity', extractedValue: '52 g', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(c)', notes: 'Accurate SI metric units (g).' },
        { field: 'mrp', label: 'Retail Sale Price (MRP)', extractedValue: '₹ 20.00 (incl. of all taxes)', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(e)', notes: 'Includes Unit Sale Price: ₹ 0.38/g.' },
        { field: 'mfgDate', label: 'Date of Packing / Mfg', extractedValue: '09/2026', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(d)', notes: 'Clear month and year declaration.' },
        { field: 'expiryDate', label: 'Date of Expiry / Best Before', extractedValue: '03/2027', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(d)', notes: 'Specified expiry date.' },
        { field: 'consumerCare', label: 'Consumer Care Redressal', extractedValue: '1800-111-4567 / care@tastycrunch.co.in', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(g)', notes: 'Complete contact mechanism.' },
      ],
    },
    violations: [],
    isEdited: false,
  },
  {
    id: 'INS-2026-0092',
    userId: 'id_gov_01',
    userName: 'Rajesh Sharma (Inspector)',
    userRole: 'official',
    governmentId: 'GOV-LM-2024-889',
    timestamp: new Date(Date.now() - 3600000 * 20).toISOString(),
    productName: 'QuickBite Snack Co. Potato Chips (Defective)',
    category: 'Snacks & Confectionery',
    complianceScore: 28,
    complianceStatus: 'NON_COMPLIANT',
    enforcementAction: 'SEIZURE_RECOMMENDED',
    inspectorRemarks: 'Pasted MRP sticker, missing manufacturer address and misleading quantity declaration ("approx 50g"). Seizure notice issued.',
    imageUrls: ['https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=800&q=80'],
    extractedData: {
      productName: 'QuickBite Snack Co. Potato Chips',
      brandName: 'Snack Co.',
      genericCommodityName: 'Potato Chips',
      category: 'Snacks & Confectionery',
      manufacturerDetails: {
        name: 'Snack Co. (address omitted)',
        address: 'Not provided on label',
        isSpecified: false,
        isMarketerDifferent: true,
        marketerDetails: 'Snack Co.',
      },
      netQuantity: {
        declaredValue: 'approx 50g',
        numericValue: 50,
        unit: 'g',
        isUnitValid: false,
        standardPackMatch: false,
        misleadingTermsUsed: ['approx'],
        clearSpaceCompliant: false,
      },
      mrpDetails: {
        declaredMRP: '₹ 25 (sticker pasted)',
        numericMRP: 25.0,
        hasInclAllTaxes: false,
        isStickerPasted: true,
        isAltered: true,
      },
      dates: {
        mfgDate: 'NOT PRINTED',
        expiryDate: 'NOT PRINTED',
        bestBefore: 'NOT PRINTED',
      },
      consumerCare: {
        hasConsumerCare: false,
        nameOrDesignation: '',
        phoneOrTollFree: '',
        email: '',
        postalAddress: '',
        completeness: 'MISSING',
      },
      languageAndVisibility: {
        isHindiOrEnglish: false,
        languagesDetected: ['Regional only'],
        isColorContrasting: false,
        fontSizeEstimatedPt: 6,
        isFontSizeAdequate: false,
        isMoldedOrBlown: false,
      },
      declarationsTable: [
        { field: 'mrp', label: 'MRP Declaration', extractedValue: '₹ 25 (Pasted sticker)', isValid: false, status: 'INCORRECT', ruleCitation: 'Rule 18(1)', notes: 'Alteration of printed MRP with pasted sticker is strictly prohibited.' },
        { field: 'netQty', label: 'Net Quantity', extractedValue: 'approx 50g', isValid: false, status: 'MISLEADING', ruleCitation: 'Rule 8(d)', notes: 'Prohibited misleading word "approx" used in quantity declaration.' },
        { field: 'mfgDate', label: 'Mfg Date', extractedValue: 'Missing', isValid: false, status: 'MISSING', ruleCitation: 'Rule 6(1)(d)', notes: 'Month & Year of manufacture missing entirely.' },
        { field: 'expiryDate', label: 'Date of Expiry / Best Before', extractedValue: 'Missing', isValid: false, status: 'MISSING', ruleCitation: 'Rule 6(1)(d)', notes: 'Expiry / best before date missing on perishable commodity.' },
        { field: 'mfgAddress', label: 'Manufacturer Address', extractedValue: 'Missing', isValid: false, status: 'MISSING', ruleCitation: 'Rule 6(1)(a)', notes: 'Physical address of manufacturer/packer missing.' },
      ],
    },
    violations: [
      {
        id: 'viol_01',
        field: 'mrp',
        title: 'Pasted MRP Sticker',
        description: 'Pasted MRP sticker altering retail price',
        severity: 'CRITICAL',
        legalSection: 'Rule 18(1) / Section 36(1)',
        recommendation: 'Compound fee ₹25,000 or seizure under Section 15',
      },
      {
        id: 'viol_02',
        field: 'netQuantity',
        title: 'Misleading Expression in Quantity',
        description: 'Use of expression "approx" qualifying net weight',
        severity: 'MAJOR',
        legalSection: 'Rule 8(d) / Section 39',
        recommendation: 'Notice to show cause within 15 days',
      },
      {
        id: 'viol_03',
        field: 'manufacturerDetails',
        title: 'Missing Manufacturer Address',
        description: 'Absence of manufacturer/packer physical postal address',
        severity: 'CRITICAL',
        legalSection: 'Rule 6(1)(a) / Section 36(1)',
        recommendation: 'Seizure of batch from distribution premises',
      },
    ],
    isEdited: false,
  },
  {
    id: 'INS-2026-0093',
    userId: 'id_gov_01',
    userName: 'Rajesh Sharma (Inspector)',
    userRole: 'official',
    governmentId: 'GOV-LM-2024-889',
    timestamp: new Date(Date.now() - 3600000 * 48).toISOString(),
    productName: 'PureVita Whole Wheat Atta 5kg',
    category: 'Rice / Flour / Atta / Rawa / Suji',
    complianceScore: 100,
    complianceStatus: 'COMPLIANT',
    enforcementAction: 'VERIFIED_COMPLIANT',
    inspectorRemarks: 'Complete metric and statutory declaration under Second Schedule. Registered manufacturer license verified.',
    imageUrls: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80'],
    extractedData: {
      productName: 'PureVita Whole Wheat Atta 5kg',
      brandName: 'PureVita',
      genericCommodityName: 'Whole Wheat Atta',
      category: 'Rice / Flour / Atta / Rawa / Suji',
      manufacturerDetails: {
        name: 'Pavitra Agro Foods Pvt. Ltd.',
        address: 'G.T. Road, Karnal, Haryana - 132001',
        isSpecified: true,
        isMarketerDifferent: false,
        marketerDetails: 'Pavitra Agro Foods Pvt. Ltd.',
        countryOfOrigin: 'India',
      },
      netQuantity: {
        declaredValue: '5 kg',
        numericValue: 5,
        unit: 'kg',
        isUnitValid: true,
        standardPackMatch: true,
        misleadingTermsUsed: [],
        clearSpaceCompliant: true,
      },
      mrpDetails: {
        declaredMRP: '₹ 245.00 (incl. of all taxes)',
        numericMRP: 245.0,
        hasInclAllTaxes: true,
        unitSalePrice: '₹ 49.00 / kg',
        isStickerPasted: false,
        isAltered: false,
      },
      dates: {
        mfgDate: '08/2026',
        expiryDate: '11/2026',
        bestBefore: '3 Months from packing',
      },
      consumerCare: {
        hasConsumerCare: true,
        nameOrDesignation: 'Consumer Care Cell',
        phoneOrTollFree: '1800-200-8899',
        email: 'support@pavitrafoods.in',
        postalAddress: 'P.O. Box 132001, Karnal, Haryana',
        completeness: 'COMPLETE',
      },
      languageAndVisibility: {
        isHindiOrEnglish: true,
        languagesDetected: ['Hindi', 'English'],
        isColorContrasting: true,
        fontSizeEstimatedPt: 12,
        isFontSizeAdequate: true,
        isMoldedOrBlown: false,
      },
      declarationsTable: [
        { field: 'commodityName', label: 'Name of Commodity', extractedValue: 'Whole Wheat Atta', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(b)', notes: 'Generic commodity declared clearly.' },
        { field: 'mfgName', label: 'Manufacturer Name & Address', extractedValue: 'Pavitra Agro Foods Pvt. Ltd., Karnal', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(a)', notes: 'Complete postal address with PIN.' },
        { field: 'netQty', label: 'Net Quantity', extractedValue: '5 kg', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(c)', notes: 'Schedule II standard size (5kg) with SI unit.' },
        { field: 'mrp', label: 'Retail Sale Price (MRP)', extractedValue: '₹ 245.00 (incl. of all taxes)', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(e)', notes: 'Includes Unit Sale Price: ₹ 49/kg.' },
        { field: 'mfgDate', label: 'Date of Packing', extractedValue: '08/2026', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(d)', notes: 'Legible month and year.' },
        { field: 'expiryDate', label: 'Date of Expiry / Best Before', extractedValue: '11/2026', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(d)', notes: 'Expiry / best before date clearly specified.' },
        { field: 'consumerCare', label: 'Consumer Care Cell', extractedValue: '1800-200-8899 / support@pavitrafoods.in', isValid: true, status: 'CORRECT', ruleCitation: 'Rule 6(1)(g)', notes: 'Full redressal contact.' },
      ],
    },
    violations: [],
    isEdited: false,
  },
];
